import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeaderComponent from "@/layouts/header/HeaderComponent";
import { SidemenuComponent } from "@/layouts/sidemenu/SidemenuComponent";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  <html lang="en">
  <body className={`${inter.variable} ${inter.variable} antialiased bg-[#F8F9FF]`}>
    <div className="flex flex-col min-h-screen">
      <HeaderComponent />
      <div className="flex flex-1">
        <SidemenuComponent />
        <main className="flex-1 p-4 overflow-auto">{children}</main>
      </div>
    </div>
  </body>
</html>
  );
}
